# Generated by Django 4.0.6 on 2022-07-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='specs',
        ),
    ]
