# Generated by Django 4.0.6 on 2022-07-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='note',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
